apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: my-test-bridge
spec:
  containers:
    - name: test-ipam-pod
      image: centos/tools
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 300; done;" ]