apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: example-sriov-network
  namespace: openshift-sriov-network-operator
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.4.225/28",
      "exclude": [
       "192.168.4.229/30",
       "192.168.4.236/32"
      ]
    }
  vlan: 0
  resourceName: sriovlegacy
  networkNamespace: default