name: Determine Target Branch

on:
  push:
    tags:
      - 'v*'

jobs:
  find-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Target Branch
        shell: bash
        run: |
          set -e  # Fail on errors
          set -x  # Enable trace mode for debugging

          # Extract the tag name from GITHUB_REF
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Extracted TAG_NAME: $TAG_NAME"

          if [[ "$TAG_NAME" =~ beta ]]; then
            echo "Detected 'beta' tag. Setting branch to 'master'."
            echo "TARGET_BRANCH=master" >> $GITHUB_ENV
          else
            # Match version tags like v24.10.0 or v24.10.0-rc.3
            if [[ "$TAG_NAME" =~ ^v([0-9]+\.[0-9]+)\. ]]; then
              RELEASE_BRANCH="v${BASH_REMATCH[1]}.x"
              echo "Parsed release branch: $RELEASE_BRANCH"
              echo "TARGET_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
            else
              echo "Failed to parse tag name: $TAG_NAME"
              exit 1
            fi
          fi

          # Confirm the TARGET_BRANCH value
          echo "Determined target branch: $TARGET_BRANCH"

      - name: Print Target Branch
        run: |
          echo "The target branch is ${{ env.TARGET_BRANCH }}"
